### PR TITLE
refactor(ValidateRequestBody): reduce cyclomatic complexity and indent

### PR DESCRIPTION
**Pull request by nickajacks1**
Use the early-out pattern to reduce code complexity.
None of the existing logic should have changed, and all tests pass.

@daveshanley Can you fact check me at line 40? At this point, are there any errors that could occur here?

### CODE REVIEW

**Comment by daveshanley** [comment]
A missing content type, I mean there is nothing to do, there is no work to perform, there is no way to know what to validate.

As soon as the coverage is back at 100%, I can merge this. I can't let coverage drop on this codebase, the tests are the guarantee it is as robust as we can make it.

**Comment by nickajacks1** [comment]
> As soon as the coverage is back at 100%, I can merge this
Sure, I will take a crack at it.

From a branch coverage perspective though, the coverage remains identical since there is no logical change from the existing code.  It's highly likely that there are more of these uncovered branches elsewhere in the code - for example, see validate_request.go.  It also has a highly indented function that may or may not be missing test cases.
Going beyond line coverage may be effective in boosting the robustness of this library.

**Comment by nickajacks1** [comment]
> A missing content type, I mean there is nothing to do, there is no work to perform, there is no way to know what to validate.

Instantly passing validation is probably wrong as it might let an invalid body through to later handlers.  I'm thinking it would be better to return `errors.RequestContentTypeNotFound`

**Comment by nickajacks1** [comment]
By the way, I created TestValidateBody_MediaTypeHasNullSchema to reach 100% coverage, but it's technically testing an invalid openapi doc.  A media type object must have a schema field (which can itself be empty, but then that doesn't cover the Schema == nil check).

**Pull request merged**
